name: Integration Workflow

on:
  push:
    paths:
      - ".github/workflows/integration-workflow.yaml"
      - "integration/**/*"

jobs:
  integration_job:
    runs-on: ubuntu-latest
    name: Integration tests
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: yarn install
      - name: Boot up Server
        run: docker-compose -f ./integration/js/docker-compose.yaml up -d
      - name: Run tests
        run: yarn workspace @gtoru/js-integration test
