name: JS Client Workflow

on:
  push:
    paths:
      - "client/js/**/*"

jobs:
  eslint-job:
    runs-on: ubuntu-18.04
    name: Check ESLint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "13.8"
      - name: Install ESLint
        run: yarn workspace @gtoru/js-client add eslint
      - name: Run ESLint
        run: yarn workspace @gtoru/js-client lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: yarn workspace @gtoru/js-client install
      - name: build client
        run: yarn workspace @gtoru/js-client build

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: yarn workspace @gtoru/js-client install
      - name: run unit tests
        run: yarn workspace @gtoru/js-client test

  integration_tests:
    runs-on: ubuntu-latest
    needs: [eslint-job, run-tests, build]
    name: Integration tests
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: yarn install
      - name: Boot up Server
        run: docker-compose -f ./integration/js/docker-compose.yaml up -d
      - name: Run tests
        run: yarn workspace @gtoru/js-integration test

  npm-publish:
    runs-on: ubuntu-latest
    needs: [eslint-job, build, run-tests, integration_tests]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: yarn install
      - name: build
        run: yarn workspace @gtoru/js-client build
      - uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com"
          scope: "@gtoru"
      - run: yarn lerna publish from-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
