name: JS Client Workflow

on:
  push:
    paths:
      - "client/js/*"
      - ".github/workflows/js-client-workflow.yaml"

jobs:
  eslint-job:
    runs-on: ubuntu-18.04
    name: Check ESLint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "13.8"
      - name: Install ESLint
        run: yarn workspace @gtoru/js-client add eslint
      - name: Run ESLint
        run: yarn workspace @gtoru/js-client lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: yarn workspace @gtoru/js-client install
      - name: build client
        run: yarn workspace @gtoru/js-client build

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: yarn workspace @gtoru/js-client install
      - name: run unit tests
        run: yarn workspace @gtoru/js-client test

  npm-publish:
    runs-on: ubuntu-latest
    needs: [eslint-job, build, run-tests]
    steps:
      - uses: actions/checkout@v2
        if: ${{ github.ref }} == 'master'
      - name: install deps
        run: yarn workspace @gtoru/js-client install
      - name: build
        run: yarn workspace @gtoru/js-client build
      - name: prepare npmrc
        run: echo "registry=https://npm.pkg.github.com/gtoru" > .npmrc
        working-directory: client/js
      - name: publish
        run: npm publish
        working-directory: client/js
